# Generated by Django 4.1 on 2023-07-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_free_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
